version: '3'
services:
  aspace:
    container_name: aspace
    build: .
    ports:
      - '8080:8080'
      - '8081:8081'
    depends_on: 
      - db
    environment: 
      APPCONFIG_DB_URL: 'jdbc:mysql://db:3306/archivesspace?useUnicode=true&characterEncoding=UTF-8&user=as&password=as123&useSSL=false'
    volumes: 
      - aspace_data:/archivesspace/data
      - aspace_logs:/archivesspace/logs
  db:
    image: mysql:8.0.25
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db:/var/lib/mysql
    expose:
      - '3306'
    environment: 
      MYSQL_DATABASE: archivesspace
      MYSQL_USER: as
      MYSQL_PASSWORD: as123
volumes: 
  aspace_data:
  aspace_logs:
  db: