version: '3'
services:
  aspace:
    container_name: aspace
    build: .
    ports:
      - '8080:8080'
      - '8081:8081'
    depends_on:
      - db
    environment:
      APPCONFIG_DB_URL: 'jdbc:mysql://host.docker.internal:3306/archivesspace?useUnicode=true&characterEncoding=UTF-8&user=as&password=as123&useSSL=false&allowPublicKeyRetrieval=true'
    volumes:
      - aspace_data:/archivesspace/data
      - aspace_logs:/archivesspace/logs
volumes:
  aspace_data:
  aspace_logs:
